Regular Update 01/04/2026

diff --git a/.github/workflows/release-foss.yml b/.github/workflows/release-foss.yml
--- a/.github/workflows/release-foss.yml
+++ b/.github/workflows/release-foss.yml
@@ -16,25 +16,43 @@ jobs:
 
             - name: Verify GitHub token (GH_PAT) is set
               run: |
-                  if [ -z "${{ secrets.GH_PAT }}" ]; then
-                      echo "❌ GitHub token 'GH_PAT' is missing."
-                      echo "Please set the 'GH_PAT' secret in your repository settings. Must be a token classic with Permissions read:org, repo, workflow"
-                      exit 1
-                  else
-                      echo "✅ GitHub token 'GH_PAT' is set."
-                  fi
+                if [ -z "${{ secrets.GH_PAT }}" ]; then
+                    echo "❌ GitHub token 'GH_PAT' is missing."
+                    echo "Please set the 'GH_PAT' secret in your repository settings. Must be a token classic with Permissions read:org, repo, workflow"
+                    exit 1
+                else
+                    echo "✅ GitHub token 'GH_PAT' is set."
+                fi
 
             - name: Set up JDK 17
               uses: actions/setup-java@v3
               with:
                   java-version: '17'
                   distribution: 'temurin'
+                  cache: gradle
 
             - name: Make Gradle wrapper executable
               run: chmod +x ./gradlew
 
+            - name: Add swap (reduce OOM risk)
+              run: |
+                # If a swapfile already exists / is enabled, disable and remove it
+                if sudo swapon --show | grep -qE '^/swapfile\b'; then
+                  sudo swapoff /swapfile
+                fi
+                if [ -f /swapfile ]; then
+                  sudo rm -f /swapfile
+                fi
+
+                sudo fallocate -l 6G /swapfile
+                sudo chmod 600 /swapfile
+                sudo mkswap /swapfile
+                sudo swapon /swapfile
+                free -h
+
             - name: Build APK with Gradle
-              run: ./gradlew :app:assembleProdWebsiteRelease
+              run: ./gradlew :app:assembleProdWebsiteRelease --no-daemon --max-workers=2
+              # run: ./gradlew :app:assembleProdWebsiteRelease
 
             - name: List merged manifest files
               run: find app/build/intermediates/merged_manifests/ -name "AndroidManifest.xml"
